--- arch/arm/mach-msm/Makefile
+++ arch/arm/mach-msm/Makefile
@@ -424,3 +424,4 @@
 obj-$(CONFIG_WALL_CLK_SYSFS) += wallclk_sysfs.o
 obj-$(CONFIG_ARCH_RANDOM) += early_random.o
 obj-$(CONFIG_PERFMAP) += perfmap.o
+obj-$(CONFIG_LCD_KCAL) += board_kcal.o kcal_ctrl.o
